#!/bin/bash
#Author : yuxuan

CONF='/usr/local/nginx/conf/nginx.conf'
UPGRADE=/usr/local/nginx/conf/nginx.conf.upgrade
NORMAL=/usr/local/nginx/conf/nginx.conf.normal

rm $CONF
ln -s $UPGRADE $CONF
/sbin/service nginxsrv reload 
